import type { UApp } from "@/lib/uapps/types";

export const uappsDemoData: UApp[] = [
  {
    id: "user-smart-finance",
    name: "Smart Finance",
    description:
      "مدیریت ساده و هوشمند امور مالی شخصی.",
    category: "مالی و مدیریت",
    source: "user",
    sourceLabel: "ساخته‌شده توسط کاربر",
    platform: "web",
    platformLabel: "Web",
    type: "web-app",
    typeLabel: "نرم‌افزار تحت وب",
    status: "available",
    statusLabel: "فعال",
    icon: "₿",
    accent: "blue",
    href: "/uapps",
    featured: true,
    verified: false,
  },
  {
    id: "user-task-flow",
    name: "Task Flow",
    description:
      "مدیریت کارها و برنامه‌ریزی روزانه.",
    category: "بهره‌وری",
    source: "user",
    sourceLabel: "ساخته‌شده توسط کاربر",
    platform: "android",
    platformLabel: "Android",
    type: "installable",
    typeLabel: "قابل نصب",
    status: "available",
    statusLabel: "فعال",
    icon: "✓",
    accent: "purple",
    href: "/uapps",
    featured: true,
    verified: false,
  },
  {
    id: "user-quick-notes",
    name: "Quick Notes",
    description:
      "ثبت سریع ایده‌ها و یادداشت‌های روزانه.",
    category: "یادداشت",
    source: "user",
    sourceLabel: "ساخته‌شده توسط کاربر",
    platform: "multi",
    platformLabel: "چند پلتفرمی",
    type: "hybrid",
    typeLabel: "چند پلتفرمی",
    status: "available",
    statusLabel: "فعال",
    icon: "✎",
    accent: "green",
    href: "/uapps",
    featured: true,
    verified: true,
  },
  {
    id: "user-auto-desk",
    name: "Auto Desk",
    description:
      "خودکارسازی فرایندهای تکراری.",
    category: "اتوماسیون",
    source: "user",
    sourceLabel: "ساخته‌شده توسط کاربر",
    platform: "windows",
    platformLabel: "Windows",
    type: "installable",
    typeLabel: "قابل نصب",
    status: "development",
    statusLabel: "در حال توسعه",
    icon: "↗",
    accent: "orange",
    href: "/uapps",
  },
  {
    id: "uniqe-my-u",
    name: "My U",
    description:
      "مرکز مدیریت هویت، سرویس‌ها و فعالیت‌های شما.",
    category: "اکوسیستم Uniqe",
    source: "uniqe",
    sourceLabel: "ساخته‌شده توسط Uniqe",
    platform: "web",
    platformLabel: "Web",
    type: "web-app",
    typeLabel: "نرم‌افزار تحت وب",
    status: "available",
    statusLabel: "فعال",
    icon: "U",
    accent: "blue",
    href: "/my",
    featured: true,
    verified: true,
  },
  {
    id: "uniqe-uapps",
    name: "UApps",
    description:
      "مرکز کشف و دسترسی به نرم‌افزارهای دیجیتال.",
    category: "نرم‌افزار",
    source: "uniqe",
    sourceLabel: "ساخته‌شده توسط Uniqe",
    platform: "web",
    platformLabel: "Web",
    type: "web-app",
    typeLabel: "نرم‌افزار تحت وب",
    status: "available",
    statusLabel: "فعال",
    icon: "◆",
    accent: "purple",
    href: "/uapps",
    featured: true,
    verified: true,
  },
  {
    id: "uniqe-uweb",
    name: "UWeb",
    description:
      "فضای مدیریت پروژه‌ها و خدمات وب.",
    category: "وب",
    source: "uniqe",
    sourceLabel: "ساخته‌شده توسط Uniqe",
    platform: "web",
    platformLabel: "Web",
    type: "web-app",
    typeLabel: "نرم‌افزار تحت وب",
    status: "available",
    statusLabel: "فعال",
    icon: "W",
    accent: "green",
    href: "/my-uweb",
    verified: true,
  },
  {
    id: "uniqe-uservice",
    name: "UService",
    description:
      "اتصال کاربران به خدمات تخصصی.",
    category: "خدمات",
    source: "uniqe",
    sourceLabel: "ساخته‌شده توسط Uniqe",
    platform: "web",
    platformLabel: "Web",
    type: "web-app",
    typeLabel: "نرم‌افزار تحت وب",
    status: "coming-soon",
    statusLabel: "به‌زودی",
    icon: "S",
    accent: "orange",
    href: "/uapps",
    verified: true,
  },
  {
    id: "google-notion",
    name: "Notion",
    description:
      "Workspace for notes, projects and knowledge.",
    category: "Productivity",
    source: "google-play",
    sourceLabel: "Google Play",
    platform: "android",
    platformLabel: "Android",
    type: "installable",
    typeLabel: "قابل نصب",
    status: "available",
    statusLabel: "فعال",
    icon: "N",
    accent: "black",
    href: "/uapps",
  },
  {
    id: "google-canva",
    name: "Canva",
    description:
      "Create designs, presentations and visual content.",
    category: "Design",
    source: "google-play",
    sourceLabel: "Google Play",
    platform: "android",
    platformLabel: "Android",
    type: "installable",
    typeLabel: "قابل نصب",
    status: "available",
    statusLabel: "فعال",
    icon: "C",
    accent: "pink",
    href: "/uapps",
  },
  {
    id: "google-todoist",
    name: "Todoist",
    description:
      "Organize tasks and manage your daily work.",
    category: "Productivity",
    source: "google-play",
    sourceLabel: "Google Play",
    platform: "android",
    platformLabel: "Android",
    type: "installable",
    typeLabel: "قابل نصب",
    status: "available",
    statusLabel: "فعال",
    icon: "✓",
    accent: "red",
    href: "/uapps",
  },
  {
    id: "appstore-figma",
    name: "Figma",
    description:
      "Collaborative interface design and prototyping.",
    category: "Design",
    source: "app-store",
    sourceLabel: "App Store",
    platform: "ios",
    platformLabel: "iOS",
    type: "installable",
    typeLabel: "قابل نصب",
    status: "available",
    statusLabel: "فعال",
    icon: "F",
    accent: "purple",
    href: "/uapps",
  },
];